<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit3ab508a4a9b25e1a89df42091099140a
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Phossa2\\Uuid\\' => 13,
            'Phossa2\\Shared\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Phossa2\\Uuid\\' => 
        array (
            0 => __DIR__ . '/..' . '/phossa2/uuid/src/Uuid',
        ),
        'Phossa2\\Shared\\' => 
        array (
            0 => __DIR__ . '/..' . '/phossa2/shared/src/Shared',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit3ab508a4a9b25e1a89df42091099140a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit3ab508a4a9b25e1a89df42091099140a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
