<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Phossa2\\Uuid\\' => array($vendorDir . '/phossa2/uuid/src/Uuid'),
    'Phossa2\\Shared\\' => array($vendorDir . '/phossa2/shared/src/Shared'),
);
